version: "3.8"
services:

  api_server:
    image: shalireza/api_server:0.1
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      - scheduler
      - manager
      - namespace
    environment:
      PYTHONPATH: "/app"
      API_SERVER_USER: "root"
      SCHEDULER_HOST: "http://scheduler:8000"
      MANAGER_HOST: "http://manager:8000"
      NAMESPACE_HOST: "http://namespace:8000"
    ports:
      - target: 8000
        published: 8000
        protocol: tcp    
  scheduler:
    image: shalireza/scheduler:0.3
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

    environment:
      PYTHONPATH: "/app"
      SCHEDULER_USER: "root"
      RABBITMQ_HOST: "172.16.30.30"
      RABBITMQ_PORT: "5672"
      DATABASE_URL: "postgres://postgres:ddlHJkUCXkjDI5YFCB4l@172.16.10.231:5432/bo"
      NAMESPACE_SERVER_HOST: "namespace"
      NAMESPACE_SERVER_PORT: "8000"
  manager:
    image: shalireza/manager:0.1 
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

    environment:
      PYTHONPATH: "/app"
      MANAGER_USER: "root"
      RABBITMQ_HOST: "172.16.30.30"
      RABBITMQ_PORT: "5672"
      DATABASE_URL: "postgres://postgres:ddlHJkUCXkjDI5YFCB4l@172.16.10.231:5432/bo"
      NAMESPACE_SERVER_HOST: "namespace"
      NAMESPACE_SERVER_PORT: "8000"
      MINIO_ADDRESS: "172.16.18.242:9000"
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
  namespace:
    image: shalireza/namespace:0.1 
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

    environment:
      PYTHONPATH: "/app"
      NAMESPACE_USER: "root"
      DATABASE_URL: "postgres://postgres:ddlHJkUCXkjDI5YFCB4l@172.16.10.231:5432/bo"
 
