SECRET_KEY = "8h2?GW=rw@GkyDAXLL!-_z4r?6Cr96c!NjRd%!G#qj=a>*AJ1IL$r96FXNhy3_F4"
MANAGER_HOST = 'localhost'
MANAGER_PORT = '8000'
LOGIN_PATH = '/api/module/login'
HOST = 'localhost'
PORT = 9000
NAME = 'mysql'
KAFKA_HOST = None
KAFKA_PORT = None
KAFKA_TOPIC = None
