"""Add CronJobModel

Revision ID: b62466cc7ebb
Revises: 
Create Date: 2021-05-17 02:17:26.087995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62466cc7ebb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler.cronjob',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('technology', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('minute', sa.String(), nullable=True),
    sa.Column('hour', sa.String(), nullable=True),
    sa.Column('day_of_month', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler.cronjob')
    # ### end Alembic commands ###
