"""Add label column to CronJobModel table

Revision ID: df14460665ef
Revises: b62466cc7ebb
Create Date: 2021-05-17 03:03:20.828377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df14460665ef'
down_revision = 'b62466cc7ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler.cronjob', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler.cronjob', 'label')
    # ### end Alembic commands ###
