import os

PYTHONPATH = os.getenv('PYTHONPATH')
API_SERVER_USER = os.getenv('API_SERVER_USER')
SCHEDULER_HOST = os.getenv('SCHEDULER_HOST')
MANAGER_HOST = os.getenv('MANAGER_HOST')
NAMESPACE_HOST = os.getenv('NAMESPACE_HOST')
